name: Behave

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  step-1:
    runs:
      using: 'docker'
      image: 'Dockerfile'
      run: "bash entrypoint.sh"