on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  behave:
    runs:
      using: 'docker'
      image: 'Dockerfile'
      run: "bash entrypoint.sh"