name: Behave

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  step-1:
  - name: GitHub Docker Action
    uses: matootie/github-docker@v3.1.0

  - name: Print Image URL
    run: echo ${{ steps.publish.outputs.imageURL }}    