name: Docker Image CI

on: [push]

jobs:

  ci:

    runs-on: ubuntu-latest    

    steps:
    - uses: actions/checkout@v1

    - name: Setup ...
      run: CONTAINER_NAME=behave

    - name: Building image ...
      run: docker build -t $CONTAINER_NAME  .

    - name: Run ...
      run: docker container run $CONTAINER_NAME behave